obj:
  _target_: monai.networks.nets.swin_unetr 
  img_size: ${roi_size}
  in_channels: 1
  out_channels: 1
  feature_size: 64
  use_checkpoint: true
pretrained_weight: "./pretrained/model_swinvit.pt"
