obj:
  _target_: monai.networks.nets.unet.UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2
pretrained_weight: null
