dataset_dir: /data/snubhcvc/raw_coco_format/mpxa
splits_path: splits.json
annotation_filename: train_val.json
img_dirname: images
mask_dirname: masks
prob: 0.2
rotation_range: [-0.26, 0.26]
spatial_size: [512, 512]

train_dataloader:
  _target_: monai.data.DataLoader
  batch_size: 16
  dataset:
    _target_: medseg.datasets.mpxa.MpxaDataset
    dataset_dir: ${dataset.dataset_dir}
    annotation_filename: ${dataset.annotation_filename}
    img_dirname: ${dataset.img_dirname}
    splits_path: ${dataset.splits_path}
    mode: train
    mask_dirname: ${dataset.mask_dirname}
    transform: 
      _target_: monai.transforms.Compose
      transforms:
        - _target_: monai.transforms.LoadImaged
          keys: ["image", "mask"]
          reader: "NumpyReader"
        - _target_: monai.transforms.EnsureChannelFirstd
          keys: ["image", "mask"]
        # - _target_: monai.transforms.RepeatChanneld
        #   keys: ["image"]
        #   repeats: 3
        - _target_: monai.transforms.Resized
          keys: ["image", "mask"]
          spatial_size: ${dataset.spatial_size}
          mode: ["bilinear", "nearest"]
        - _target_: monai.transforms.RandRotated
          keys: ["image", "mask"]
          prob: ${dataset.prob}
          range_x: ${dataset.rotation_range}
          range_y: ${dataset.rotation_range}
          mode: ["bilinear", "nearest"]
        - _target_: monai.transforms.RandZoomd
          keys: ["image", "mask"]
          prob: ${dataset.prob}
          min_zoom: 0.8
          max_zoom: 1.2
        - _target_: monai.transforms.RandGaussianNoised
          keys: ["image"]
          prob: ${dataset.prob}
        - _target_: monai.transforms.RandGaussianSmoothd
          keys: ["image"]
          prob: ${dataset.prob}
        - _target_: monai.transforms.RandScaleIntensityd
          keys: ["image"]
          factors: 0.3
          prob: ${dataset.prob}
        - _target_: monai.transforms.RandAdjustContrastd
          keys: ["image"]
          prob: ${dataset.prob}
        - _target_: monai.transforms.EnsureTyped
          keys: ["image", "mask"]

val_dataloader:
  _target_: monai.data.DataLoader
  batch_size: 1
  dataset:
    _target_: medseg.datasets.mpxa.MpxaDataset
    dataset_dir: ${...dataset_dir}
    annotation_filename: ${dataset.annotation_filename}
    img_dirname: ${dataset.img_dirname}
    splits_path: ${dataset.splits_path}
    mode: val
    mask_dirname: ${dataset.mask_dirname}
    transform: 
      _target_: monai.transforms.Compose
      transforms:
        - _target_: monai.transforms.LoadImaged
          keys: ["image", "mask"]
          reader: "NumpyReader"
        - _target_: monai.transforms.EnsureChannelFirstd
          keys: ["image", "mask"]
        # - _target_: monai.transforms.RepeatChanneld
        #   keys: ["image"]
        #   repeats: 3
        - _target_: monai.transforms.Resized
          keys: ["image", "mask"]
          spatial_size: ${dataset.spatial_size}
          mode: ["bilinear", "nearest"]
        - _target_: monai.transforms.EnsureTyped
          keys: ["image", "mask"]

eval_post_pred_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: monai.transforms.Activations
      sigmoid: true
    - _target_: monai.transforms.AsDiscrete
      threshold: 0.5

eval_post_label_transforms: 
  _target_: monai.transforms.Compose
  transforms:
    - _target_: monai.transforms.AsDiscrete
      threshold: 0.5

inferer:
  _target_:
    monai.inferers.SimpleInferer

prepare_batch:
  _target_: medseg.core.utils.lambda_prepare_batch
  keys: ["image", "mask"]
