defaults:
  - _self_
  - model: unet.yaml
  - dataset: imagecas.yaml

mlflow_tracking_uri: file:///data/mlruns
experiment_name: imagecas
max_epochs: 300
num_workers: 4
device: cuda
multi_gpu: true
key_metric_name: mean_dice
roi_size: [256, 256, 128]
val_check_interval: 5

loss: 
  _target_: monai.losses.dice.DiceLoss
  # _target_: medseg.losses.cldice.clDiceLoss

optimizer: 
  _target_: torch.optim.Adam
  lr: 0.01
  weight_decay: 0.0003

lr_scheduler: 
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${max_epochs}
  eta_min: 0.0001

metrics: 
  _target_: builtins.dict
  mean_dice:
    _target_: monai.handlers.MeanDice

train_handlers:
  _target_: builtins.list

evaluate_handlers:
  _target_: builtins.list
