defaults:
  - _self_
  - model: skel_unet.yaml
  - dataset: imagecas.yaml

mlflow_tracking_uri: file:///data/mlruns
experiment_name: imagecas
max_epochs: 300
num_workers: 4
device: cuda
multi_gpu: true
key_metric_name: mean_dice
roi_size: [128, 128, 96]
val_check_interval: 5

loss: 
  - obj: 
      _target_: monai.losses.dice.DiceLoss
      sigmoid: true
    start_weight: 1.0
    end_weight: 0.3
  - obj: 
      _target_: medseg.losses.cldice.clDiceLoss
    start_weight: 0.0
    end_weight: 0.7

optimizer: 
  _target_: torch.optim.Adam
  lr: 0.01
  weight_decay: 0.0003

lr_scheduler: 
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${max_epochs}
  eta_min: 0.0001

metrics: 
  _target_: builtins.dict
  mean_dice:
    _target_: monai.handlers.MeanDice

train_handlers:
  _target_: builtins.list

evaluate_handlers:
  _target_: builtins.list
